repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.279  # Use the latest version
    hooks:
      - id: ruff
        args: [--fix]
  - repo: https://github.com/psf/black
    rev: 23.9.1  # Use the latest version
    hooks:
      - id: black
        language_version: python3
